config/routes.rb
Rails.application.routes.draw do
  resources :branches
  resources :contacts
  root to: 'branches#index'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
	#belongs_to :contacts
	has_many :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	#has_many :branches
	belongs_to :branch

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.order("name ASC").page(params[:page]).per(5)
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :city, :state,:iata)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    @branches = Branch.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @branches=Branch.all
  
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @branches=Branch.all
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name_employee, :phone_number, :email, :sucursal, :mobile_phone, :stus_flag,:branch_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Ciudad %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :Estado %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :Clave%><br>
    <%= f.text_field :iata%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/branches/edit.html.erb
<h1>Editing Branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Listing Branches</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.city %></td>
        <td><%= branch.state %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @branches %>
<br>

<%= link_to 'New Branch', new_branch_path ,{class:'btn btn-info'}%>
</div>

app/views/branches/new.html.erb
<h1>New Branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @branch.state %>
</p>
<p>
	<strong>Clave:</strong>
	<%= @branch.iata %>
</p>
<% @branch.contacts.each do |contact| %>
	-<div><%= contact.name_employee %></div>
	<%end%>

<br>
<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Nombre %>
    <%= f.text_field :name_employee,{class:'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :Telefono %>
    <%= f.text_field :phone_number,{class:'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email,{class:'form-control',type:'email',placeholder:'Email'} %>
  </div>
  <div class="form-group">
    <%= f.label :Sucursal %>
    <%= f.select 'branch_id', options_for_select(@branches.collect{ |u| [u.iata, u.id] }) %>
  </div>
  <div class="form-group">
    <%= f.label :Celular %>
    <%= f.text_field :mobile_phone,{class:'form-control'} %>
  </div>
  <div class="checkbox">
    <%= f.label :stus_flag do %>
    <%= f.check_box :stus_flag %> Activo?
    <%end%> 
  </div>
  
    <%= f.submit :Guardar,{class:'btn btn-success'}%>
  
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Listing Contacts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name employee</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Sucursal</th>
      <th>Mobile phone</th>
      <th>Stus flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name_employee %></td>
        <td><%= contact.phone_number %></td>
        <td><%= contact.email %></td>
        <td><%= contact.branch_id %></td>
        <td><%= contact.mobile_phone %></td>
        <td><%= contact.stus_flag %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Contact', new_contact_path,{class:'btn btn-success'} %>
</div>

app/views/contacts/new.html.erb
<div class="container">
	<h1>New Contact</h1>
		<%= render 'form' %>
		<%= link_to 'Back', contacts_path %>
		
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name employee:</strong>
  <%= @contact.name_employee %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>
<% @branch.contacts.each do |contact|  %>
<p>
  <strong>Sucursal:</strong>
  <%= contact.sucursal %>
</p>
<%end%>








<p>
  <strong>Mobile phone:</strong>
  <%= @contact.mobile_phone %>
</p>

<p>
  <strong>Stus flag:</strong>
  <%= @contact.stus_flag %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhoneDirectory1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- Compiled and minified CSS -->
  
<style>
 html,body{
	margin: 0px;
	font-family: 'Lato', sans-serif;
	overflow-x:hidden;
 }
 a,a:visited{
	color: inherit;
	text-decoration: none;
 } body { padding-top: 70px; }

 

</style>

</head>
<body>
  <%=render 'navbar' %>
	<%= yield %>	

<h1>esta es una prueba de sublime con git</h1>
</body>
</html>